# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-15 02:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseno', models.CharField(max_length=10)),
                ('coursename', models.CharField(max_length=40)),
                ('deptname', models.CharField(max_length=20)),
                ('credit', models.IntegerField(default=3)),
            ],
        ),
    ]
