# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-15 03:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enroll',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('courseno', models.CharField(max_length=10)),
                ('grade', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('dept', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('gpa', models.FloatField()),
            ],
        ),
    ]
