# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-16 12:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_enroll_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Enroll',
        ),
    ]
