# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-16 12:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_delete_enroll'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enroll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.FloatField()),
                ('courseno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Course', verbose_name='courseno')),
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Student', verbose_name='id')),
            ],
        ),
    ]
