# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-21 05:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_auto_20161116_2129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='id',
        ),
        migrations.AlterField(
            model_name='course',
            name='courseno',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
